name: Lint

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v2
      - run: brew install swiftlint
      - uses: actions/checkout@v4
      - name: Run lint
        run: swiftlint
